alias g="git"
alias gti="git"
alias pull="git pull"
alias push="git push"
alias push.tags="git push --tags"
alias st="git st"
alias stash="git stash"
alias pop="git stash pop"
alias spp="stash;pull;pop"

alias gflow="git flow"